{{ $_ := set . "deployAction" "update" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pgo-deploy
  namespace: pgo
  labels:
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: postgres-operator
    meta.helm.sh/release-namespace: pgo
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
{{ template "deployerJob.spec" . }}
