apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-${PGCLUSTER}-for-pgo5
spec:
  template:
    spec:
      containers:
      - command:
        - bash
        - -ce
        - |-
          echo "Preparing ${PGCLUSTER}'s volumes for PGO v5.x"
          echo "pgdata_pvc=${PGDATA_PVC} repo_pvc=${REPO_PVC}"
          echo "Current PG data directory volume contents:" ; ls -lh "/pgdata"
          echo "Now updating PG data directory..."
          [ -d "/pgdata/${PGDATA_PVC}" ] && mv "/pgdata/${PGDATA_PVC}" "/pgdata/pg${PG_VERSION}"
          rm -f "/pgdata/pg${PG_VERSION}/patroni.dynamic.json"
          echo "Updated PG data directory contents:" ; ls -lh "/pgdata"
          echo "PG Data directory preparation complete"
          echo "Current repo directory volume contents:" ; ls -lh "/pgbackrest"
          echo "Now updating repo directory..."
          [ -d "/pgbackrest/${PGCLUSTER}-backrest-shared-repo" ] && \
            mv "/pgbackrest/${PGCLUSTER}-backrest-shared-repo/"* "/pgbackrest"
          rm -rf "/pgbackrest/${PGCLUSTER}-backrest-shared-repo"
          echo "Updated repo directory contents:" ; ls -lh "/pgbackrest"
          echo "Repo directory preparation complete"
          echo "The volumes for cluster ${PGCLUSTER}'s are now prepared for PGO v5.x"
        image: ${IMAGE}
        name: pgo-upgrade
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /pgdata
          name: postgres-data
        - mountPath: /pgbackrest
          name: pgbackrest
      restartPolicy: Never
      securityContext:
        fsGroup: 26
        runAsNonRoot: true
        supplementalGroups:
        - ${SUPPLEMENTAL_GROUPS}
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: ${PGDATA_PVC}
      - name: pgbackrest
        persistentVolumeClaim:
          claimName: ${REPO_PVC}
